version: "3.9"

services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
      - 4321:5432
    environment:
      POSTGRES_DB: jobs_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data
  web:
    build: .
    command: npm run dev:watch
    depends_on:
      - postgres
    ports:
      - 5000:5000
      - 5555:5555
    environment:
      DATABASE_URL: postgres://postgres@postgres/jobs_dev
      PORT: 5000
      SECRET: "super secret"
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules
volumes:
  postgres-data:
  nodemodules: {}
